### ISSUE TITLE
Add install task

### ISSUE THREAD

**Issue by slashplusweb** [bambamboole/laravel-cms-b5-environment#7]
- make packages folder & clone laravel-cms repo (if not existing)
- composer-cms install
- composer install
- npm-cms install
- npm install
- link-assets
- template for config.local (with traefik)
- artisan cms:migrate

**Comment by bambamboole** [comment]
This is a good thing.

Following steps:
* composer-cms install
* composer install
* npm-cms install
* npm-cms run dev
* npm install
* npm run dev
* link-assets
* template for config.local (with traefik)
* artisan cms:migrate
* phpunit-cms

can you send a pr for this pls :-)

**Comment by slashplusweb** [comment]
see PR #10
would you rather do the git clone manually, or is that ok?

Moreover the `artisan cms:migrate` task fails currently, because of the missing cms database. i wonder why we dont simply use one database called docker OR cms? if we need both, then maybe we could do something like this: https://github.com/abagayev/docker-bootstrap-collection/tree/master/mysql-few-databases
