### ISSUE TITLE
Add db tasks for better collaboration

### ISSUE THREAD

**Issue by slashplusweb** [bambamboole/laravel-cms-b5-environment#8]
It should be possible to import and export databases using default db tasks

**Comment by bambamboole** [comment]
We can merge this, but I don't think that we need this. There should be a proper seeder for dummy data in the package. It would be a mess if we have to hand databases to other persons.

**Comment by slashplusweb** [comment]
> There should be a proper seeder for dummy data in the package.
I agree.

> It would be a mess if we have to hand databases to other persons.
I disagree - why should this be a mess at all? This can become handy for example, when experiencing issues that at first cant be reproduced.

**Comment by bambamboole** [comment]
ok :-)
